org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=true
org.gradle.parallel=true

# Mod Properties
mod.version=build-11
maven_group=me.noramibu
archives_base_name=nora-tweaks

# 26.2 dependency versions
minecraft_version=26.2
loader_version=0.19.3
fabric_api_version=0.152.1+26.2
meteor_version=26.2
baritone_version=26.1
xpple_cubiomes_version=0.0.0-2026.6.29.1782739186+b12a5325c8a195fa99711ed2052a4fc9cac077a8
